apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-statique
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mionitra/nginx-kubernetes-gitops.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true       # supprime du cluster ce qui a été retiré du Git
      selfHeal: true     # corrige automatiquement toute dérive manuelle
    syncOptions:
      - CreateNamespace=true
