apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: site-statique-rs
  labels:
    app: site-statique
spec:
  replicas: 6
  selector:
    matchLabels:
      app: site-statique
  template:
    metadata:
      labels:
        app: site-statique
    spec:
      containers:
        - name: nginx
          image: ghcr.io/mionitra/site-statique:v1.0.0
          imagePullPolicy: IfNotPresent   # important : ne pas aller chercher sur un registre distant
          ports: 
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-creds
---
apiVersion: v1
kind: Service
metadata:
  name: site-statique-svc
spec:
  selector:
    app: site-statique   # doit matcher les labels des Pods du ReplicaSet
  ports:
    - protocol: TCP
      port: 80            # port exposé par le Service
      targetPort: 80       # port du conteneur nginx
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-statique-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - site-statique.local
      secretName: site-statique-tls
  rules:
    - host: site-statique.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: site-statique-svc
                port:
                  number: 80
